services:
  backend:
    build:
      context: .
      dockerfile: .
    container_name: neomovies-backend
    ports:
      - "4000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://db:27017/neomovies
      - BASE_URL=http://localhost:3000
      - FRONTEND_URL=http://localhost:3001
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: neomovies-database
    ports:
      - "27017:27017"
    volumes:
      - ~/files/docker/neomovies-database:/data/db
    restart: unless-stopped
